version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify_success:
          requires:
            - build

  notify_success:
    docker:
      - image: mcr.microsoft.com/powershell
    steps:
      - run:
          name: Notify Success
          command: |
            $title = "Build succeeded!"
            $message = "Your build has succeeded on CircleCI."
            $code = @"
            [Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
            [System.Windows.Forms.MessageBox]::Show("$message", "$title", "OK", "Information")
            "@
            powershell -Command $code
